name: Various PHP Install

on:
    push:
        branches:
            - main

jobs:
    various_php_install:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php:
                    - 7.2
                    - 8.0
                    - 8.1
                    - 8.2
                    - 8.3

        name: "Install on PHP ${{ matrix.php }}"

        steps:
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   run: composer require tomasvotruba/unused-public --dev --ansi
